baseURL = "http://www.yoedistro.org/"
languageCode = "en-us"
title = "The Yoe Distribution"
theme = "hextra"

[params]
  featured_image = "/images/yoe-logo.png"
  github = "https://github.com/YoeDistro"
  logo = "/images/yoe-logo.png" # Expecting square dimensions
